### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by zachtyll** [Forsakringskassan/designsystem#110]
Hello!

I'd like to translate [the documentation](https://forsakringskassan.github.io/designsystem/latest/index.html) into English to facilitate the usage of English-speaking developers.

I read the contribution guidelines and found this:

> All dokumentation på webbplatsen ska vara på svenska. Undantag är referenser till koden.

Which translates to "All documentation on the website should be in Swedish. References in the code are excepted."

I'd like to raise a discussion on whether this is a useful requirement for an open-source project and if it would be possible to provide English as an alternate translation of the Swedish source material on the website.

**Comment by kristinalindstrom** [comment]
Thank you for your feedback. 
We understand your thoughts but Försäkringskassan is a swedish authority and we have a requirement to have all documentation in swedish. This is what we can share right now.
